version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  webserver:
    build: .
    container_name: webserver
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
